version: '3'

services:
  dnsv6-internal-server:
    build: .
    # image: widecamp1903/unbound-v6
    container_name: dnsv6-internal-server
    restart: unless-stopped
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
    network_mode: host
