network:
  ethernets:
    ens192:
      addresses: [10.0.156.130/16]
      routes:
      - to: 0.0.0.0/0
        via: 10.0.0.1
        metric: 1
      nameservers:
        addresses: [1.1.1.1]
    ens160:
      addresses: [203.178.156.130/26, "2001:200:0:ff20::156:130/64"]
      routes:
      - to: 0.0.0.0/0
        via: 203.178.156.129
        metric: 10
      gateway6: 2001:200:0:ff20::1
      nameservers:
        addresses: [1.1.1.1, "2606:4700:4700::1111"]
  version: 2
